# Generated by Django 5.2 on 2025-04-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_sale',
            new_name='hot_sale',
        ),
    ]
