# Generated by Django 5.2 on 2025-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_on_sale_product_hot_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='best_selling',
            new_name='best_sellers',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hot_sale',
            new_name='hot_sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.BooleanField(default=False),
        ),
    ]
